AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  <%= functionName %>:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      MemorySize: 256
      Timeout: 10
      Environment:
        Variables: 
          AuthorName: <%= author %>
